[package]
name = "csv_parser_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.78"
reqwest = "0.11.6"
wasm-bindgen-futures = "0.4.28"

[lib]
crate-type = ["cdylib"]
